# Generated by Django 3.2 on 2023-11-03 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miniapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productslist',
            name='price',
            field=models.IntegerField(default=100),
        ),
    ]
